### ISSUE TITLE
加词时报错

### ISSUE THREAD

**Issue by FRANK641** [zhb2000/anki-marker#5]
![image](https://github.com/zhb2000/anki-marker/assets/76161945/276f151f-ad9f-4c8f-b99a-9ed919bafcc7)
![image](https://github.com/zhb2000/anki-marker/assets/76161945/284cf772-a572-45a4-b23a-163f6f9832cc)
大佬，词咋加不进去啊。

**Comment by FRANK641** [comment]
![image](https://github.com/zhb2000/anki-marker/assets/76161945/475164d3-7752-4773-bbfb-28a895a0ebc9)

**Comment by zhb2000** [comment]
可能是 AnkiConnect 插件的服务没有正常启动，你可以按下面的方法检查一下。

重启 Anki 软件，AnkiConnect 插件也会跟着重启。

检查 AnkiConnect 服务是否正常启动：用浏览器访问 http://localhost:8765 ，正常的话可以看到 `AnkiConnect v.6` 这样的文字。

检查 AnkiConnect 提供的 API 是否可以正常调用：Win + R 输入 `powershell` 并回车，将以下命令粘贴到 powershell 中

```powershell
Invoke-WebRequest -Uri 'http://localhost:8765' `
    -Method Post `
    -Headers @{"Content-Type"="application/json"} `
    -Body '{"action": "createDeck", "params": {"deck": "Others"}, "version": 6}' `
    -UseBasicParsing
```

保持 Anki 软件处于打开的状态，按下回车执行该命令。该命令会向 AnkiConnect 发送一个 POST 请求，以创建一个名为 Others 的牌组。正常的话，该命令会返回类似 `Content: {"result": 1719034705324, "error": null}` 这样的的东西，你的 Anki 软件中也会新增一个名为 Others 的牌组。

**Comment by FRANK641** [comment]
感谢。已经解决了。顺便想问下大佬能在卡片模板上加东西吗？比如能够朗读例句和添加笔记

**Comment by zhb2000** [comment]
> 感谢。已经解决了。顺便想问下大佬能在卡片模板上加东西吗？比如能够朗读例句和添加笔记

这个卡片模板自带一个“笔记”字段，所以你可以在 Anki 软件里给卡片添加笔记。后续我会在划词助手里加一个按钮，这样操作起来更方便。

朗读例句实现起来比较麻烦，因为 Anki 取消了通过 URL 播放音频的功能，必须把音频文件下载下来。我研究下有没有方便一点的方法。
